modLoader="javafml"
loaderVersion="[${forge_api_version},)"
license="MIT"
[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Nick Robson"
description="${mod_description}"
[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="[${forge_api_version},)"
    ordering="NONE"
    side="BOTH"
[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17,1.18)"
    ordering="NONE"
    side="BOTH"